
######### MAIN #########

homeassistant:
    # authentication
    auth_providers:
      - type: trusted_networks
        trusted_networks:
          - 192.168.1.0/24
        allow_bypass_login: true
      - type: homeassistant
    # location
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    # elevation
    elevation: !secret home_elevation
    # temperature unit
    unit_system: metric
    # time zone
    time_zone: Europe/Madrid
    # name
    name: Home

    # integration definition in separate folder
    # https://www.home-assistant.io/docs/configuration/packages/
    packages: !include_dir_named integrations

    # customize
    customize: !include customize.yaml

config:

frontend:
      
sun:
      
system_health:
      
history:
      

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

########## LOGGING ##########
logger:
  default: warning
  logs:
      homeassistant.components.homematic: warning
      # locationsharinglib: debug
