
######### MAIN #########

homeassistant:
    # authentication
    auth_providers:
      - type: trusted_networks
        trusted_networks:
          - 192.168.1.0/24
        allow_bypass_login: true
      - type: homeassistant
    # location
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    # elevation
    elevation: !secret home_elevation
    # temperature unit
    unit_system: metric
    # time zone
    time_zone: Europe/Madrid
    # name
    name: Home

    # integration definition in separate folder
    # https://www.home-assistant.io/docs/configuration/packages/
    packages: !include_dir_named integrations

    # customize
    customize: !include customize.yaml