title: Security
icon: 'mdi:lock'
id: security
path: security
badges: []
type: custom:grid-layout
layout:
  grid-template-columns: 25% 25% 25% 25%
  grid-template-rows: auto
  grid-template-areas: |
    "doorbell living-room garden ."
  mediaquery:
    "(max-width: 600px)":
      grid-template-columns: 100%
      grid-template-areas: |
        "doorbell"
        "living-room"
        "garden"
    "(max-width: 900px)": 
      grid-template-columns: 50% 50%
      grid-template-areas: |
        "doorbell living-room"
        "garden ."
    "(max-width: 1600px)": 
      grid-template-columns: 33% 33% 33%
      grid-template-areas: |
        "doorbell living-room garden"
cards:
  - type: vertical-stack
    view_layout:
      grid-area: doorbell
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.doorbell
            live_provider: ha
            title: Doorbell
  - type: vertical-stack
    view_layout:
      grid-area: living-room
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.living_room
            live_provider: ha
            title: Living Room
  - type: vertical-stack
    view_layout:
      grid-area: garden
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.garden
            live_provider: ha
            title: Garden
